# Generated by Django 4.0.3 on 2022-05-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0002_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreplacement',
            name='cnicNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addreplacement',
            name='firstName',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='addreplacement',
            name='imgKey',
            field=models.URLField(default='none'),
        ),
        migrations.AlterField(
            model_name='addreplacement',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
