# Generated by Django 4.0.3 on 2022-05-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
