# Generated by Django 4.0.3 on 2022-05-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0004_alter_addreplacement_cnicnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreplacement',
            name='designation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addreplacement',
            name='firstName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='addreplacement',
            name='imgKey',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='addreplacement',
            name='lastName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='addreplacement',
            name='shift',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='addreplacement',
            name='shiftTiming',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
