# Generated by Django 4.0.3 on 2022-05-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0006_accounts_adminusers_article_cisessions_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminusers',
            options={'managed': True},
        ),
    ]
