# Generated by Django 4.0.3 on 2022-05-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0007_alter_adminusers_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminusers',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
